version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/.
    env_file:
      - ./.env
    volumes:
      - /home/hbay/data/mariadb_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    networks:
      - wpress
      
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/.
    env_file:
      - ./.env
    volumes:
      - /home/hbay/data/wordpress_data:/var/www/html
    # ports:
    #   - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - wpress

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - /home/hbay/data/wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wpress

volumes:
  data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wpress:
    driver: bridge