version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build:
      context: /home/hbay/srcs/requirements/mariadb/.
    env_file:
      - /home/hbay/srcs/.env
    volumes:
      - data:/var/lib/mysql
    # ports:
    #   - "3306:3306"

  wordpress:
    container_name: wordpress
    build:
      context: /home/hbay/srcs/requirements/wordpress/.
    env_file:
      - /home/hbay/srcs/.env
    volumes:
      - ./wordpress_data:/var/www/html
    # ports:
    #   - "8080:8080"
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: /home/hbay/srcs/requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - ./wordpress_data:/var/www/html
    depends_on:
      - wordpress

volumes:
  data:
    driver: local
  wordpress_data:
    driver: local