FROM debian:buster


RUN apt-get update && \
    apt-get install -y \
    mariadb-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /run/mysqld && \
    chown mysql:mysql /run/mysqld

EXPOSE 3306

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/.
COPY tools/database.sql /etc/mysql/database.sql
CMD ["bash", "-c", "mysql_install_db --user=mysql && mysqld"]