FROM debian:buster

RUN apt-get update && \
    apt-get install -y \
    mariadb-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /run/mysqld && \
    chown mysql:mysql /run/mysqld

EXPOSE 3306

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/
COPY tools/database.sql /etc/mysql/database.sql
COPY tools/maria.sh /usr/local/bin/maria.sh
RUN chmod +x /usr/local/bin/maria.sh

#ENTRYPOINT ["/usr/local/bin/maria.sh"]
CMD ["mysqld"]
