FROM debian:buster
RUN apt-get update && \
    apt-get install -y php-fpm php-mysql wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir -p /var/www/html/wordpress  /run/php
RUN wget https://wordpress.org/latest.tar.gz && \
    tar -xzf latest.tar.gz -C /var/www/html/wordpress --strip-components=1 && \
    rm latest.tar.gz
COPY ./conf/www.conf /etc/php/7.3/fpm/pool.d/.
COPY ./tools/wordpress.sh /usr/local/bin/wordpress.sh
RUN chmod +x /usr/local/bin/wordpress.sh
CMD ["/usr/local/bin/wordpress.sh"]