CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'hbay'@'%' IDENTIFIED BY 'root123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'hbay'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';

FLUSH PRIVILEGES;