FROM debian:buster
RUN apt-get update &&\
    apt-get install -y \
    nginx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
EXPOSE 80
COPY conf/default /etc/nginx/sites-available/.
CMD ["nginx", "-g", "daemon off;"]
